### PR TITLE
Added Flatpak support

### PR DESCRIPTION
**Pull request by Mailaender**
This just unhardcodes some paths and adds metadata according to the https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps standard.

### CODE REVIEW

**Comment by Mailaender** [comment]
Yes, it just works because Qt already has the neccessary portals.

**Comment by Mailaender** [comment]
You can test it at https://github.com/flathub/flathub/pull/3730 where you are of course also invited.

**Comment by dridk** [comment]
Could you remind me to add flatpak installation in README when it is ready ?

**Comment by Mailaender** [comment]
Check back tomorrow on https://flathub.org/apps/details/io.github.labsquare.CutePeaks I am also curious if it plays the gif animation.

**Pull request merged**
